lib{concurrentqueue}: hxx{**}
{
  cxx.export.poptions += "-I$src_base/moodycamel" "-I$src_root"
}

if ($cxx.target.class != 'windows')
{
    cxx.libs += "-lpthread"
    lib{concurrentqueue}: cxx.export.libs += "-lpthread"
}

hxx{**}:
{
  install         = include/concurrentqueue/
  install.subdirs = true
}

lib{concurrentqueue}: cxx.pkgconfig.include = include/ include/concurrentqueue/moodycamel/
